spring:
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    client-id: test-id
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 5s
      group-id: sandbox-group-id
    streams:
      application-id: streams-app-id

application:
  kafka:
    topic:
      input: start
      output: finish